# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'RWDeviceEngineDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'CustomEngine','~> 0.1.6'
  # Pods for RWDeviceEngineDemo

end
